import type { BlockSpec } from '../types';

/**
 * Khối điều khiển luồng chương trình.
 * Khối có thân nhận mã phần thân qua tham số trùng tên với `bodies`.
 */
export const CONTROL_BLOCKS: BlockSpec[] = [
  {
    type: 'ino_on_start',
    category: 'control',
    message: 'khi bấm vào nút Chạy',
    args: [],
    shape: 'hat',
    tooltip: 'Chương trình bắt đầu chạy từ đây',
    toJS: () => '',
    toCpp: () => '',
  },
  {
    type: 'ino_forever',
    category: 'control',
    message: 'lặp mãi',
    args: [],
    shape: 'statement',
    bodies: [{ name: 'BODY' }],
    tooltip: 'Lặp lại các lệnh bên trong không ngừng',
    toJS: (a) => `while (true) {\n${a.BODY}await robot.tick();\n}\n`,
    toCpp: (a) => `while (true) {\n${a.BODY}}\n`,
  },
  {
    type: 'ino_repeat',
    category: 'control',
    message: 'lặp lại %1 lần',
    args: [{ name: 'TIMES', kind: 'number', value: 10, min: 1, max: 1000 }],
    shape: 'statement',
    bodies: [{ name: 'BODY' }],
    tooltip: 'Lặp lại các lệnh bên trong số lần đã chọn',
    toJS: (a) => `for (let i = 0; i < ${a.TIMES}; i++) {\n${a.BODY}await robot.tick();\n}\n`,
    toCpp: (a) => `for (int i = 0; i < ${a.TIMES}; i++) {\n${a.BODY}}\n`,
  },
  {
    type: 'ino_repeat_until',
    category: 'control',
    message: 'lặp cho đến khi %1',
    args: [{ name: 'COND', kind: 'input', check: 'Boolean' }],
    shape: 'statement',
    bodies: [{ name: 'BODY' }],
    tooltip: 'Lặp lại các lệnh bên trong cho tới khi điều kiện đúng thì thoát ra',
    toJS: (a) => `while (!(${a.COND || 'false'})) {\n${a.BODY}await robot.tick();\n}\n`,
    toCpp: (a) => `while (!(${a.COND || 'false'})) {\n${a.BODY}}\n`,
  },
  {
    type: 'ino_if_else',
    category: 'control',
    message: 'nếu %1 thì',
    args: [{ name: 'COND', kind: 'input', check: 'Boolean' }],
    shape: 'statement',
    bodies: [{ name: 'DO' }, { name: 'ELSE', label: 'ngược lại' }],
    tooltip: 'Điều kiện đúng thì làm nhóm trên, sai thì làm nhóm dưới',
    toJS: (a) => `if (${a.COND || 'false'}) {\n${a.DO}} else {\n${a.ELSE}}\n`,
    toCpp: (a) => `if (${a.COND || 'false'}) {\n${a.DO}} else {\n${a.ELSE}}\n`,
  },
  {
    type: 'ino_break',
    category: 'control',
    message: 'thoát khỏi vòng lặp',
    args: [],
    shape: 'statement',
    tooltip: 'Dừng vòng lặp đang chạy và đi tiếp xuống lệnh phía dưới',
    toJS: () => `break;\n`,
    toCpp: () => `break;\n`,
  },
  {
    type: 'ino_wait',
    category: 'control',
    message: 'đợi %1 giây',
    args: [{ name: 'SECONDS', kind: 'number', value: 1, min: 0, max: 60 }],
    shape: 'statement',
    tooltip: 'Dừng chương trình trong khoảng thời gian đã chọn rồi chạy tiếp',
    toJS: (a) => `await robot.wait(${a.SECONDS});\n`,
    toCpp: (a) => `delay(${a.SECONDS} * 1000);\n`,
  },
  {
    type: 'ino_wait_until',
    category: 'control',
    message: 'đợi cho đến khi %1',
    args: [{ name: 'COND', kind: 'input', check: 'Boolean' }],
    shape: 'statement',
    tooltip: 'Dừng lại cho tới khi điều kiện đúng thì chạy tiếp',
    toJS: (a) => `while (!(${a.COND || 'false'})) { await robot.tick(); }\n`,
    toCpp: (a) => `while (!(${a.COND || 'false'})) { delay(10); }\n`,
  },
];
