import type { BlockSpec } from '../types';

/** Khối chuyển động — điều khiển hai động cơ bánh xe */
export const MOTION_BLOCKS: BlockSpec[] = [
  {
    type: 'ino_forward',
    category: 'motion',
    message: 'đi thẳng với tốc độ %1 trong %2 giây',
    args: [
      { name: 'SPEED', kind: 'number', value: 50, min: 0, max: 100 },
      { name: 'SECONDS', kind: 'number', value: 1, min: 0, max: 60 },
    ],
    shape: 'statement',
    tooltip: 'Robot đi thẳng về phía trước trong khoảng thời gian đã chọn',
    toJS: (a) => `await robot.forward(${a.SPEED}, ${a.SECONDS});\n`,
    toCpp: (a) => `ino.driveForward(${a.SPEED});\ndelay(${a.SECONDS} * 1000);\nino.stop();\n`,
  },
  {
    type: 'ino_backward',
    category: 'motion',
    message: 'đi lùi với tốc độ %1 trong %2 giây',
    args: [
      { name: 'SPEED', kind: 'number', value: 50, min: 0, max: 100 },
      { name: 'SECONDS', kind: 'number', value: 1, min: 0, max: 60 },
    ],
    shape: 'statement',
    tooltip: 'Robot lùi lại phía sau',
    toJS: (a) => `await robot.backward(${a.SPEED}, ${a.SECONDS});\n`,
    toCpp: (a) => `ino.driveBackward(${a.SPEED});\ndelay(${a.SECONDS} * 1000);\nino.stop();\n`,
  },
  {
    type: 'ino_turn_left',
    category: 'motion',
    message: 'rẽ trái với tốc độ %1',
    args: [{ name: 'SPEED', kind: 'number', value: 50, min: 0, max: 100 }],
    shape: 'statement',
    tooltip: 'Robot quay sang trái, chạy cho tới khi gặp lệnh khác',
    toJS: (a) => `await robot.turnLeft(${a.SPEED});\n`,
    toCpp: (a) => `ino.turnLeft(${a.SPEED});\n`,
  },
  {
    type: 'ino_turn_right',
    category: 'motion',
    message: 'rẽ phải với tốc độ %1',
    args: [{ name: 'SPEED', kind: 'number', value: 50, min: 0, max: 100 }],
    shape: 'statement',
    tooltip: 'Robot quay sang phải, chạy cho tới khi gặp lệnh khác',
    toJS: (a) => `await robot.turnRight(${a.SPEED});\n`,
    toCpp: (a) => `ino.turnRight(${a.SPEED});\n`,
  },
  {
    type: 'ino_turn_left_for',
    category: 'motion',
    message: 'rẽ trái với tốc độ %1 trong %2 giây',
    args: [
      { name: 'SPEED', kind: 'number', value: 50, min: 0, max: 100 },
      { name: 'SECONDS', kind: 'number', value: 1, min: 0, max: 60 },
    ],
    shape: 'statement',
    tooltip: 'Robot quay trái trong khoảng thời gian đã chọn rồi tự dừng',
    toJS: (a) => `await robot.turnLeftFor(${a.SPEED}, ${a.SECONDS});\n`,
    toCpp: (a) => `ino.turnLeft(${a.SPEED});\ndelay(${a.SECONDS} * 1000);\nino.stop();\n`,
  },
  {
    type: 'ino_turn_right_for',
    category: 'motion',
    message: 'rẽ phải với tốc độ %1 trong %2 giây',
    args: [
      { name: 'SPEED', kind: 'number', value: 50, min: 0, max: 100 },
      { name: 'SECONDS', kind: 'number', value: 1, min: 0, max: 60 },
    ],
    shape: 'statement',
    tooltip: 'Robot quay phải trong khoảng thời gian đã chọn rồi tự dừng',
    toJS: (a) => `await robot.turnRightFor(${a.SPEED}, ${a.SECONDS});\n`,
    toCpp: (a) => `ino.turnRight(${a.SPEED});\ndelay(${a.SECONDS} * 1000);\nino.stop();\n`,
  },
  {
    type: 'ino_forward_on',
    category: 'motion',
    message: 'chạy thẳng với tốc độ %1',
    args: [{ name: 'SPEED', kind: 'number', value: 50, min: 0, max: 100 }],
    shape: 'statement',
    tooltip: 'Robot đi thẳng liên tục cho tới khi gặp lệnh khác. Dùng trong vòng lặp dò line.',
    toJS: (a) => `await robot.forwardOn(${a.SPEED});\n`,
    toCpp: (a) => `ino.driveForward(${a.SPEED});\n`,
  },
  {
    type: 'ino_backward_on',
    category: 'motion',
    message: 'chạy lùi với tốc độ %1',
    args: [{ name: 'SPEED', kind: 'number', value: 50, min: 0, max: 100 }],
    shape: 'statement',
    tooltip: 'Robot lùi liên tục cho tới khi gặp lệnh khác',
    toJS: (a) => `await robot.backwardOn(${a.SPEED});\n`,
    toCpp: (a) => `ino.driveBackward(${a.SPEED});\n`,
  },
  {
    type: 'ino_drive',
    category: 'motion',
    message: 'chạy động cơ trái %1 phải %2',
    args: [
      { name: 'LEFT', kind: 'number', value: 50, min: -100, max: 100 },
      { name: 'RIGHT', kind: 'number', value: 50, min: -100, max: 100 },
    ],
    shape: 'statement',
    tooltip: 'Đặt tốc độ riêng cho từng bánh. Số âm là quay ngược.',
    toJS: (a) => `await robot.drive(${a.LEFT}, ${a.RIGHT});\n`,
    toCpp: (a) => `ino.drive(${a.LEFT}, ${a.RIGHT});\n`,
  },
  {
    type: 'ino_stop',
    category: 'motion',
    message: 'dừng động cơ',
    args: [],
    shape: 'statement',
    tooltip: 'Dừng cả hai bánh xe',
    toJS: () => `await robot.stop();\n`,
    toCpp: () => `ino.stop();\n`,
  },
];
